Replacing some CultureInfo.CurrentCulture occurrences
microsoft/Power-Fx pull request #1530
Opened 2023-05-26 16:39 UTC by anderson-joyle

Issue #1474.

2023-05-26 16:54 UTC, LucGenetier commented
✅ No public API change.

2023-05-26 19:58 UTC, LucGenetier commented
✅ No public API change.

2023-05-26 22:46 UTC, LucGenetier commented
✅ No public API change.

2023-05-30 20:02 UTC, MikeStall commented on src/libraries/Microsoft.PowerFx.Core/Errors/ErrorUtils.cs
> -                    sb.AppendFormat(locale ?? CultureInfo.CurrentCulture, message, args);
>CurrentCulture [](http://example.com/codeflow?start=58&length=14)

Can we be confident this change isn't breaking power Apps?

2023-05-30 20:02 UTC, MikeStall requested changes
:clock1:

2023-05-30 20:03 UTC, MikeStall commented
Can we be confident this change isn't breaking power Apps? PA runs in a dedicated process - does PA rely on setting CurrentCulture anywhere?

2023-05-31 15:58 UTC, LucGenetier commented
✅ No public API change.

2024-02-20 17:23 UTC, closed without merging