Draft. Checking if the implementation is in the right path.
microsoft/Power-Fx pull request #834
Opened 2022-11-11 02:27 UTC by anderson-joyle

Issue #829

2022-11-11 02:35 UTC, BruceHaley commented
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.PowerFx.Connectors.dll**
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.PowerFx.Core.dll**
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.PowerFx.Interpreter.dll**
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.PowerFx.LanguageServerProtocol.dll**
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.PowerFx.Transport.Attributes.dll**

<!-- DO NOT DELETE THIS COMMENT. -->

2022-11-11 03:42 UTC, BruceHaley commented
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.PowerFx.Connectors.dll**
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.PowerFx.Core.dll**
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.PowerFx.Interpreter.dll**
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.PowerFx.LanguageServerProtocol.dll**
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.PowerFx.Transport.Attributes.dll**

<!-- DO NOT DELETE THIS COMMENT. -->

2022-11-11 05:04 UTC, BruceHaley commented
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.PowerFx.Connectors.dll**
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.PowerFx.Core.dll**
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.PowerFx.Interpreter.dll**
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.PowerFx.LanguageServerProtocol.dll**
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.PowerFx.Transport.Attributes.dll**

<!-- DO NOT DELETE THIS COMMENT. -->

2022-11-11 21:12 UTC, BruceHaley commented
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.PowerFx.Connectors.dll**
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.PowerFx.Core.dll**
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.PowerFx.Interpreter.dll**
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.PowerFx.LanguageServerProtocol.dll**
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.PowerFx.Transport.Attributes.dll**

<!-- DO NOT DELETE THIS COMMENT. -->

2022-11-14 19:47 UTC, BruceHaley commented
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.PowerFx.Connectors.dll**
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.PowerFx.Core.dll**
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.PowerFx.Interpreter.dll**
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.PowerFx.LanguageServerProtocol.dll**
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.PowerFx.Transport.Attributes.dll**

<!-- DO NOT DELETE THIS COMMENT. -->

2022-11-16 19:43 UTC, MikeStall commented on src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/Clear.txt
> +>> Clear(t1)
What happens when we try on literals. 


Clear([1,2,3])

2022-11-16 19:44 UTC, MikeStall commented on src/libraries/Microsoft.PowerFx.Core/Public/Values/CollectionTableValue.cs
> +            return DValue<BooleanValue>.Of(New(false));
We should ignore return value. 

[https://learn.microsoft.com/en-us/power-platform/power-fx/reference/function-clear-collect-clearcollect#clear](https://learn.microsoft.com/en-us/power-platform/power-fx/reference/function-clear-collect-clearcollect#clear)

2022-11-18 05:19 UTC, BruceHaley commented
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.PowerFx.Connectors.dll**
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.PowerFx.Core.dll**
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.PowerFx.Interpreter.dll**
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.PowerFx.LanguageServerProtocol.dll**
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.PowerFx.Transport.Attributes.dll**

<!-- DO NOT DELETE THIS COMMENT. -->

2022-11-18 18:42 UTC, BruceHaley commented
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.PowerFx.Connectors.dll**
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.PowerFx.Core.dll**
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.PowerFx.Interpreter.dll**
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.PowerFx.LanguageServerProtocol.dll**
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.PowerFx.Transport.Attributes.dll**

<!-- DO NOT DELETE THIS COMMENT. -->

2022-11-18 18:59 UTC, BruceHaley commented
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.PowerFx.Connectors.dll**
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.PowerFx.Core.dll**
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.PowerFx.Interpreter.dll**
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.PowerFx.LanguageServerProtocol.dll**
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.PowerFx.Transport.Attributes.dll**

<!-- DO NOT DELETE THIS COMMENT. -->

2022-11-22 02:08 UTC, MikeStall commented on src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/Clear.txt
> +>> Clear(t1)
Should this be [] ?  
Ie:

>> CountRows(Clear([1,2,3]) 
0

2022-11-22 02:11 UTC, MikeStall commented on src/libraries/Microsoft.PowerFx.Interpreter/Functions/Mutation/ClearFunction.cs
> +            returnType = collectionType;
Does this match the implementation?

2022-11-22 02:15 UTC, MikeStall commented on src/libraries/Microsoft.PowerFx.Interpreter/Functions/Mutation/ClearFunction.cs
> +            DType dataSourceType = argTypes[0];
>DType dataSourceType = argTypes[0]; [](http://example.com/codeflow?start=12&length=35)

not used

2022-11-22 09:51 UTC, BruceHaley commented
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.PowerFx.Connectors.dll**
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.PowerFx.Core.dll**
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.PowerFx.Interpreter.dll**
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.PowerFx.LanguageServerProtocol.dll**
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.PowerFx.Transport.Attributes.dll**

<!-- DO NOT DELETE THIS COMMENT. -->

2022-12-02 18:15 UTC, MikeStall requested changes
:clock1:

2022-12-02 18:29 UTC, BruceHaley commented
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.PowerFx.Connectors.dll**
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.PowerFx.Core.dll**
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.PowerFx.Interpreter.dll**
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.PowerFx.LanguageServerProtocol.dll**
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.PowerFx.Transport.Attributes.dll**

<!-- DO NOT DELETE THIS COMMENT. -->

2022-12-07 15:48 UTC, BruceHaley commented
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.PowerFx.Connectors.dll**
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.PowerFx.Core.dll**
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.PowerFx.Interpreter.dll**
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.PowerFx.LanguageServerProtocol.dll**
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.PowerFx.Transport.Attributes.dll**

<!-- DO NOT DELETE THIS COMMENT. -->

2022-12-29 15:20 UTC, LucGenetier commented
✅ No public API change.

2022-12-29 23:37 UTC, LucGenetier commented
✅ No public API change.

2022-12-30 00:14 UTC, LucGenetier commented
✅ No public API change.

2022-12-30 16:37 UTC, MikeStall approved these changes
:shipit:

2022-12-30 16:47 UTC, merged